### PR TITLE
Update List of Projects Using 0x Protocol

### PR DESCRIPTION
**Pull request by ziqiDev**
we create an exchange which use 0x protocol ,
@abandeali1

### CODE REVIEW

**Comment by fabioberger** [comment]
Please open a new PR once you have a working alpha that we've been able to test out. Thanks!

**Comment by dimworm** [comment]
We are restricting the alpha testing to Kovan Testnet. You can test.

**Comment by ziqiDev** [comment]
@fabioberger  I have resolve the conflicts

**Comment by fabioberger** [comment]
@ziqiDev looks like you removed TokenJar as well.

**Comment by ziqiDev** [comment]
Hello, can you help to merge code? @fabioberger

**Comment by fabioberger** [comment]
Thanks @ziqiDev!

**Pull request merged**
