### PR TITLE
add RadarRelay beta

### PR DESCRIPTION
**Pull request by brandoncurtis**

### CODE REVIEW

**Comment by fabioberger** [comment]
Thanks a lot for taking the time to write this up @brandoncurtis. I believe there might have been a miscommunication however. When I spoke with Mike and Alan at RadarRelay about wiki contributions, I meant more about Relayer agnostic informational articles that would be credited to the authoring organization. Think of this wiki similar to the Ethereum wiki. They do not contain information about projects built on Ethereum but rather about the protocol itself and how to use, test and debug it.

Within this article you wrote, there are sections that would be useful to everyone in the 0x community such as the section about how to acquire Kovan ETH and what the addresses are of the tokens registered on Kovan TokenRegistrty. Would you be willing to re-draft this article to be Relayer-agnostic? I'm also happy to take a stab at it.

Thanks again for the contribution and I hope this re-write doesn't deter you from writing additional articles in the future. We really hope to foster a collaborative atmosphere in our community and feel that everyone will benefit from it. 

Thanks again!

**Comment by fabioberger** [comment]
@brandoncurtis any reply to this?

**Comment by brandoncurtis** [comment]
@fabioberger this is in my queue—I'll revise soon!

**Comment by fabioberger** [comment]
Any update on this @brandoncurtis, otherwise we can close.

**Pull request closed without merging**
