### PR TITLE
Adding LakeProject/LakeTrade

### PR DESCRIPTION
**Pull request by polezo**

### CODE REVIEW

**Comment by fabioberger** [comment]
@polezo how do you know they are using 0x? No mention on their website.

**Comment by polezo** [comment]
Because Rahul just introcuced them in the Relayer Report. :) Along with BlockSwap 

https://blog.0xproject.com/relayer-report-13-interview-with-augurs-joey-krug-and-governance-experiments-f93e48a1ab18

I've also been following/chatting with the devs on social channels in the case of Lake, so that's how I knew before the Relayer report came out in their case

**Comment by polezo** [comment]
@fabioberger also I did just notice they do actually mention they are a 0x relayer in their onboarding process as well 

image

https://trade.lakeproject.co/trade/ZRX/WETH/charts?onboarding=1

**Comment by fabioberger** [comment]
Ah cool, thanks!

**Pull request merged**
